name: labelImg
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - gdcm=2.8.4
  - pydicom=1.1.0
  - libxml2=2.9.8
  - lxml=4.1.1
  - numpy=1.14.5
  - pillow=5.1.0
  - pip=10.0.1
  - pyqt=4.11.4
  - python=2.7.15
  - qt=4.8.7
